language: node_js
node_js:
  - "6"

env:
  - CXX=/usr/bin/g++-4.9
  - CC=/usr/bin/gcc-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

sudo: false
